# The Docker image that will be used to build your app
image: node:current
# Functions that should be executed before the build script is run
before_script:
  - yarn install
pages:
  script:
    - yarn build
    # - mkdir .public
    # - cp -r * .public
    - mv ./build public
  artifacts:
    paths:
      - public
  only:
    - main
